framework:
    cache:
        app: app_cache
        system: cache.adapter.system

        pools:
            app_cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 60
