fos_rest:

  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations

  view:
    formats: { json: true }
    view_response_listener: true
    mime_types:
      json: [ 'application/json' ]

  serializer:
    serialize_null: true

  format_listener:
    enabled: true
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: 'json' }

  param_fetcher_listener: force

  exception:
    enabled: true
    serializer_error_renderer: true
    map_exception_codes: true
    codes:
      'App\Exception\ResourceValidationException': HTTP_BAD_REQUEST
      'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': HTTP_NOT_FOUND
      'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException': HTTP_METHOD_NOT_ALLOWED
      'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': HTTP_BAD_REQUEST
      'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException': HTTP_FORBIDDEN
      'Exception': HTTP_INTERNAL_SERVER_ERROR
    messages:
      'App\Exception\ResourceValidationException': true
      'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
      'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException': true
