engines:
  phpcodesniffer:
    enabled: true

  markdownlint:
    enabled: true
    checks:
      MD029:
        enabled: false

  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false

  exclude_patterns:
    - "**/node_modules/"
    - "**/test"
    - "**/tests"
    - "tests/"
    - "**/vendor/"
    - "migrations/"
    - "diagrams/"
    - "var/"
